import {
  AnalyticsSnapshot,
  BotSettingsRecord,
  ChatMessageRecord,
  DashboardSnapshot,
  FailedQuestionRecord,
  KnowledgeDocumentRecord,
  SyncLogRecord,
} from "@/lib/admin/types";

export const mockChatMessages: ChatMessageRecord[] = [
  {
    id: "msg-1",
    sessionId: "sess-1",
    userId: "user-1",
    userQuery: "Do you have spicy nachos under PKR 500?",
    aiResponse: "Yes, I found 3 spicy snack options under your budget.",
    intent: "product",
    status: "success",
    confidenceScore: 0.94,
    responseTimeMs: 1420,
    createdAt: "2026-05-06T08:30:00.000Z",
    sourceLabel: "Catalog recommendation",
    detailsSummary: "Budget-based spicy product suggestion.",
    retrievedContext: [],
    metadata: {},
  },
  {
    id: "msg-2",
    sessionId: "sess-2",
    userId: "user-2",
    userQuery: "Track order #10452",
    aiResponse: "Your order is in transit and expected tomorrow.",
    intent: "order",
    status: "success",
    confidenceScore: 0.97,
    responseTimeMs: 1180,
    createdAt: "2026-05-06T07:52:00.000Z",
    sourceLabel: "Order lookup",
    detailsSummary: "Verified order status response.",
    retrievedContext: [],
    metadata: {},
  },
  {
    id: "msg-3",
    sessionId: "sess-3",
    userId: "user-3",
    userQuery: "Can I return a damaged item after 10 days?",
    aiResponse: "I couldn't find exact details, but here's what I know...",
    intent: "general",
    status: "failure",
    confidenceScore: 0.41,
    responseTimeMs: 2050,
    createdAt: "2026-05-06T07:31:00.000Z",
    sourceLabel: "General support",
    detailsSummary: "Policy fallback without a confirmed answer.",
    retrievedContext: [],
    metadata: {},
  },
  {
    id: "msg-4",
    sessionId: "sess-4",
    userId: "user-4",
    userQuery: "What bundle is best for movie night?",
    aiResponse: "The Family Fiesta bundle is your best fit for sharing.",
    intent: "product",
    status: "success",
    confidenceScore: 0.9,
    responseTimeMs: 1680,
    createdAt: "2026-05-06T06:49:00.000Z",
    sourceLabel: "Recommendation flow",
    detailsSummary: "Occasion-based recommendation for movie night.",
    retrievedContext: [],
    metadata: {},
  },
  {
    id: "msg-5",
    sessionId: "sess-5",
    userId: "user-5",
    userQuery: "How long does delivery take in Lahore?",
    aiResponse: "Standard delivery takes 2 to 4 business days.",
    intent: "general",
    status: "success",
    confidenceScore: 0.86,
    responseTimeMs: 990,
    createdAt: "2026-05-06T05:18:00.000Z",
    sourceLabel: "Policy knowledge",
    detailsSummary: "Shipping timeline guidance.",
    retrievedContext: [],
    metadata: {},
  },
];

export const mockFailedQuestions: FailedQuestionRecord[] = [
  {
    id: "fq-1",
    question: "Can I return a damaged item after 10 days?",
    frequency: 17,
    category: "returns",
    latestAttemptAt: "2026-05-06T07:31:00.000Z",
    suggestedAnswer:
      "Clarify damage claims window and escalation path for returns beyond the standard period.",
    resolved: false,
  },
  {
    id: "fq-2",
    question: "Which snacks are gluten free and kid-friendly?",
    frequency: 11,
    category: "product discovery",
    latestAttemptAt: "2026-05-05T18:09:00.000Z",
    suggestedAnswer: "Create a curated FAQ for dietary-safe bundles.",
    resolved: false,
  },
  {
    id: "fq-3",
    question: "Do promo codes stack with chatbot recommendations?",
    frequency: 8,
    category: "pricing",
    latestAttemptAt: "2026-05-05T12:45:00.000Z",
    suggestedAnswer: "Add a policy answer about promotion stacking rules.",
    resolved: true,
  },
];

export const mockKnowledgeDocuments: KnowledgeDocumentRecord[] = [
  {
    id: "doc-1",
    title: "Snakitos product catalog sync",
    sourceType: "shopify",
    status: "indexed",
    chunkCount: 248,
    updatedAt: "2026-05-06T06:00:00.000Z",
    summary: "Latest synced products and descriptions from Shopify.",
  },
  {
    id: "doc-2",
    title: "Returns and refund policy.pdf",
    sourceType: "pdf",
    status: "indexed",
    chunkCount: 22,
    updatedAt: "2026-05-05T15:20:00.000Z",
    summary: "Uploaded policy document used for support answers.",
  },
  {
    id: "doc-3",
    title: "Dietary FAQ",
    sourceType: "faq",
    status: "queued",
    chunkCount: 8,
    updatedAt: "2026-05-04T10:05:00.000Z",
    summary: "Manual FAQ covering healthy and allergen-sensitive products.",
  },
];

export const mockSyncLogs: SyncLogRecord[] = [
  {
    id: "sync-1",
    syncType: "products",
    status: "success",
    recordsProcessed: 386,
    startedAt: "2026-05-06T05:55:00.000Z",
    finishedAt: "2026-05-06T06:02:00.000Z",
    message: "Product sync completed and Pinecone namespace refreshed.",
  },
  {
    id: "sync-2",
    syncType: "orders",
    status: "success",
    recordsProcessed: 91,
    startedAt: "2026-05-06T05:40:00.000Z",
    finishedAt: "2026-05-06T05:43:00.000Z",
    message: "Recent orders imported for chatbot tracking intents.",
  },
  {
    id: "sync-3",
    syncType: "webhook",
    status: "failed",
    recordsProcessed: 0,
    startedAt: "2026-05-06T04:22:00.000Z",
    finishedAt: "2026-05-06T04:22:20.000Z",
    message: "products/update webhook failed signature verification.",
  },
];

export const mockBotSettings: BotSettingsRecord = {
  botName: "Snakitos AI Concierge",
  welcomeMessage: "Hey there! I can help with products, orders, and delivery questions.",
  fallbackMessage:
    "I couldn't find exact details right now. Please leave your contact and our team will help.",
  tone: "friendly",
  enableOrderTracking: true,
  enableProductRecommendations: true,
  supportEmail: "support@snakitos.com",
  supportWhatsapp: "+92-345-828-3827",
};

export const mockAnalytics: AnalyticsSnapshot = {
  behavior: {
    totalUsers: 3824,
    returningUsers: 1287,
    averageSessionDurationSec: 284,
    queriesPerSession: 4.7,
  },
  query: {
    topQuestions: [
      { label: "Track my order", value: 218 },
      { label: "Best snacks under budget", value: 176 },
      { label: "Delivery time", value: 139 },
      { label: "Healthy snacks", value: 101 },
    ],
    topProducts: [
      { label: "Family Fiesta Box", value: 142 },
      { label: "Peri Peri Nachos", value: 124 },
      { label: "Banana Chips", value: 118 },
      { label: "Movie Night Bundle", value: 95 },
    ],
    intents: [
      { name: "Product", value: 54 },
      { name: "Order", value: 27 },
      { name: "General", value: 19 },
    ],
  },
  ai: {
    successRate: 89.2,
    failureRate: 10.8,
    averageResponseTimeMs: 1340,
    confidenceBuckets: [
      { bucket: "0.0-0.4", value: 8 },
      { bucket: "0.4-0.6", value: 13 },
      { bucket: "0.6-0.8", value: 29 },
      { bucket: "0.8-1.0", value: 50 },
    ],
  },
  conversion: {
    productClicks: 942,
    addToCart: 261,
    ordersInitiated: 94,
  },
  topFailedQueries: [
    { label: "damaged item after 10 days", value: 17 },
    { label: "gluten free kid snacks", value: 11 },
    { label: "promo code stacking", value: 8 },
  ],
  failureCategories: [
    { name: "Returns", value: 38 },
    { name: "Dietary", value: 31 },
    { name: "Pricing", value: 18 },
    { name: "Shipping", value: 13 },
  ],
  dailyVolume: [
    { label: "May 1", chats: 120, sales: 11 },
    { label: "May 2", chats: 146, sales: 15 },
    { label: "May 3", chats: 134, sales: 13 },
    { label: "May 4", chats: 168, sales: 18 },
    { label: "May 5", chats: 192, sales: 22 },
    { label: "May 6", chats: 207, sales: 27 },
  ],
  hourlyUsage: [
    { hour: "00:00", chats: 4 },
    { hour: "04:00", chats: 8 },
    { hour: "08:00", chats: 16 },
    { hour: "12:00", chats: 29 },
    { hour: "16:00", chats: 33 },
    { hour: "20:00", chats: 24 },
  ],
};

export const mockDashboardSnapshot: DashboardSnapshot = {
  storeName: "Snakitos",
  metrics: [
    {
      label: "Total chats",
      value: "12.8k",
      delta: "+14.2%",
      trend: "up",
      helpText: "Across all chatbot sessions this month.",
    },
    {
      label: "Chats today",
      value: "207",
      delta: "+9.1%",
      trend: "up",
      helpText: "Compared with yesterday.",
    },
    {
      label: "Active users",
      value: "1,287",
      delta: "+6.4%",
      trend: "up",
      helpText: "Users who chatted in the last 30 days.",
    },
    {
      label: "AI success rate",
      value: "89.2%",
      delta: "-1.3%",
      trend: "down",
      helpText: "Messages marked successful by confidence and fallback logic.",
    },
    {
      label: "Failed questions",
      value: "36",
      delta: "+5 new",
      trend: "neutral",
      helpText: "Unresolved questions worth training next.",
    },
    {
      label: "Orders tracked",
      value: "418",
      delta: "+18.7%",
      trend: "up",
      helpText: "Order tracking requests handled by the bot.",
    },
    {
      label: "Product clicks",
      value: "942",
      delta: "+11.5%",
      trend: "up",
      helpText: "Clicks generated from chatbot recommendations.",
    },
  ],
  alert:
    "AI failures are elevated in returns and dietary questions. Consider adding FAQ coverage before the next campaign.",
  liveFeed: mockChatMessages,
  syncLogs: mockSyncLogs,
  failedQuestions: mockFailedQuestions,
  analytics: mockAnalytics,
};
